name: data
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./players-parser.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://data.nba.net/data/10s/prod/v1/2022/players.json
          downloaded_filename: players.json
          postprocess: ./players-parser.js
